MSA Portfolio_mobile first
mohashyne/msa-portfolio pull request #1
Opened 2023-03-24 07:39 UTC by mohashyne

In this branch:

- [ ]  Add Html file
- [ ] Add CSS file
- [ ] Add HTML&CSS linters
- [ ] Edit ReadMe file
- [ ] Add Structure and Content to  Html file
- [ ] Add styling_mobile first
- [ ] Add images

2023-03-24 08:14 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @mohashyne , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- No linter errors :+1: 
- Good use of Githu flow :+1: 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 08:14 UTC, GedeonTS commented on index.html
> +            </ul>
- Kindly make sure your design looks like the Figma design at a glance as per the project requirement, you can notice below that:
  - Your design doesn't have the background image
  - You haven't used the right font
  - Your margins and paddings need to be adjusted

Your design:
![Screenshot from 2023-03-24 10-04-54](https://user-images.githubusercontent.com/97834160/227461414-28e44af3-a258-4393-a740-967bbac98151.png)


Figma:
![Screenshot from 2023-03-24 10-10-33](https://user-images.githubusercontent.com/97834160/227462008-7d612afe-f917-429e-a1a4-660a8f603eec.png)

2023-03-24 08:14 UTC, GedeonTS commented on index.html
> +        </div>
- As per the project requirements [here](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=Now%20you%20will,aligned%20with%20flexbox.) kindly make sure to have the work section and the about section to complete this milestone :recycle:

2023-03-25 00:16 UTC, Lizdev-05 requested changes
Hi @mohashyne, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>
## Highlights
- Correct GitHub Flow 👍

- Good PR title/description 💯

- All linters passed 🏅
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 00:16 UTC, Lizdev-05 commented on index.html
> +    </section>
In other to follow HTML semantic rule, kindly change the section to a div tag. This is not a standalone section, it is part of a section. 🥺

2023-03-25 00:16 UTC, Lizdev-05 commented on index.html
> +</body>
- Kindly follow the Figma design and add the background images as we have them in the design. 🎨 🟢 
- Also, according to the project requirement, we are to make use of the colors, fonts, styles, etc as we have it in the design. Kindly implement it in your work.  🥺 🙏 
- Kindly align the icons to the left  to match the Figma design

| Your Design | Figma Design |
| :---:   | :---: | 
| <img width="383" alt="image" src="https://user-images.githubusercontent.com/73854999/227664279-56b3747c-f018-4256-b409-3ef603183cef.png">|<img width="379" alt="image" src="https://user-images.githubusercontent.com/73854999/227664356-4a434ced-3c70-4843-98d8-2dc282181829.png">|

2023-03-25 00:16 UTC, Lizdev-05 commented on index.html
> +        <label class="connect">LET'S CONNECT</label>
According to the requirement, this should either be a button or a tag since it's a call to action that will lead users to connect on your contact page, kindly change it to either a button or an a tag 🥺

2023-03-28 00:08 UTC, jerryowusu requested changes
Hi @mohashyne , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![so-close](https://user-images.githubusercontent.com/65233860/228093921-c08ebe60-a477-4240-836a-6f21953b27e0.gif)


## Highlights
Great effort so far :heavy_check_mark: 
No linter errors :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 00:08 UTC, jerryowusu commented on index.html
> +     <label class="connect">LET'S CONNECT</label>
According to the requirement, this should either be a `button` tag or an `a` tag since it's a call to action that will lead users to connect on your contact page, kindly change it to either a `button` or an `a` tag :pleading_face:

2023-03-28 00:08 UTC, jerryowusu commented on index.html
> +            <h1>Crystal logo</h1>
In order to follow the best HTML practices kindly change this to an `a` tag since the logo is always a link instead of a header.

2023-03-28 00:08 UTC, jerryowusu commented on index.html
> +     <h2>I'm Muhammad. Glad to see you!</h2>
This is the main header, so kindly consider using `h1` instead of the `h2` for semantic reasons and SEO purposes.

2023-03-28 00:08 UTC, jerryowusu commented on style.css
> +}
There is a big blank space to the right side of your design. Kindly consider removing it in order to match the actual design as shown below :point_down: 

### Your design

![Screenshot from 2023-03-28 00-06-32](https://user-images.githubusercontent.com/65233860/228093788-25298e9c-33cb-48a7-a43b-087e07a27baf.png)



### Actual design 


![Screenshot from 2023-03-28 00-06-58](https://user-images.githubusercontent.com/65233860/228093776-a464bb26-6df7-41bb-8c7a-03d96cefe01b.png)

2023-03-28 06:57 UTC, Ibizugbe approved these changes
Hi @mohashyne 👋👋, 

![VeryNiceNiceGIF](https://user-images.githubusercontent.com/64643995/228150468-77e47378-2581-48f1-8418-9c558f443d54.gif)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Linters are passing👍
- [x] Github flow practice has been used👍
- [x] Nice work implementing the changes requested by the previous reviewer👍

## Optional suggestions

- see comments below😉

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 06:57 UTC, Ibizugbe commented on index.html
> +     <p class="info">I'm a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need co
[OPTIONAL] Nice work so far, you have done a great job👍 But we can even do better by sticking to the given design😉 currently your texts are slightly different from the [design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) in terms of their font properties (size and weight)😉 see the image comparison below😉

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="300" alt="your mobile" src="https://user-images.githubusercontent.com/64643995/228152565-47417938-3547-457f-89a1-93d874dca842.png">|<img width="300" alt="headline-mobile" src="https://user-images.githubusercontent.com/64643995/228152739-aa6d4e76-8ff9-4bef-81a5-b68c0a963ee4.png">|


also, take note of the spacing between the social icons and the background image😉 don't forget we are required to stick to the[ given design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) in this milestone and it is a display of professionalism to always do so👍

2023-03-28 07:02 UTC, merged

2023-03-28 07:03 UTC, mohashyne commented
I will take note and enhance it, thank you