Finish mobile version
mohashyne/msa-portfolio pull request #2
Opened 2023-03-31 13:52 UTC by mohashyne

- [ ] add projects section
- [ ] add my 2nd project to the section
- [ ] add all my works to the projects section
- [ ] Add skills and contact form

2023-03-31 17:45 UTC, shella12 requested changes
Hi @mohashyne , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- All linters passed ✅ 
- Professional README.md ✅   
- Correct use of git flow ✅ 
- Great UI Implementation ✅ 
- Descriptive pull request ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 17:45 UTC, shella12 commented on style.css
> +}
- [ ] Please add the background color  `#E5E5E5` to the `work-card ` section to make sure you use the font and colours (background and font) defined for the [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0-1&t=WPAeJj292530Rl9r-0) as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#project--requirements) of the project to stick to the Figma template as much as possible

Figma design:

<img width="358" alt="Screenshot 2023-03-31 at 9 11 20 PM" src="https://user-images.githubusercontent.com/44798044/229184224-15043e00-61ab-4e35-ad60-9d4f887faf01.png">

Your design:

<img width="297" alt="Screenshot 2023-03-31 at 9 12 48 PM" src="https://user-images.githubusercontent.com/44798044/229184252-8228e7d2-2cc8-45ee-8e3d-fa0c8820ccef.png">

2023-03-31 17:45 UTC, shella12 commented on style.css
> +}
- [ ] Please make sure the ` .role` text of the last` work-card` looks like the `role` on the[ figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0-1&t=WPAeJj292530Rl9r-0).  

Your design:
<img width="258" alt="Screenshot 2023-03-31 at 9 14 51 PM" src="https://user-images.githubusercontent.com/44798044/229185079-bbc0a9e8-c9ae-4c41-96d6-9739dfff7b7d.png">

Figma design:

<img width="254" alt="Screenshot 2023-03-31 at 9 15 48 PM" src="https://user-images.githubusercontent.com/44798044/229185142-749d6cca-f16a-4ba3-86c2-ecba417b494c.png">

2023-03-31 17:45 UTC, shella12 commented on style.css
> +  width: 214px;
- [ ] Please make sure the margin between the card description and tech stack matches that in the figma template as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#project--requirements) of the project to make sure section has the margins (top, bottom, left, right) defined to match [figma design.](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0-1&t=WPAeJj292530Rl9r-0)

Your design:

<img width="258" alt="Screenshot 2023-03-31 at 9 14 51 PM" src="https://user-images.githubusercontent.com/44798044/229186794-9e8991e6-6248-4331-b76a-73092d992ddb.png">

Figam design:

<img width="320" alt="Screenshot 2023-03-31 at 9 15 42 PM" src="https://user-images.githubusercontent.com/44798044/229186860-8612e23c-668b-455d-b7a7-f443da1ad3de.png">

2023-03-31 17:45 UTC, shella12 commented on index.html
> +        <p class="info">I'm a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need
- [ ] The `About Myself` heading and the `info` paragraph in the figma design are aligned in a straight line. Please make sure to follow the same design guidelines.

Figma design:

<img width="356" alt="Screenshot 2023-03-31 at 9 13 00 PM" src="https://user-images.githubusercontent.com/44798044/229187597-ae591305-5b21-4160-a194-1b21589daa79.png">

Your design:

<img width="300" alt="Screenshot 2023-03-31 at 9 14 26 PM" src="https://user-images.githubusercontent.com/44798044/229187970-c5c6d34a-e362-495f-aab0-e2319950779e.png">

2023-03-31 17:45 UTC, shella12 commented on style.css
> +}
- [ ] Great job implementing the hover interaction. Please implement the interaction for active state as well as the figma template has the guidelines for pressed state as well

<img width="743" alt="Screenshot 2023-03-31 at 9 16 30 PM" src="https://user-images.githubusercontent.com/44798044/229188932-85ca8592-7975-4f8d-994a-cc3a74ba6897.png">

2023-03-31 17:45 UTC, shella12 commented on style.css
> +}
- [ ] The background-color of the tech stack in the figma design is `#F7F7F9` and not` #e5e5e5` . Please make sure to implement the same color scheme as according to the project requirements we must stick to the figma design including colors, fonts and spacing

Figam design:

<img width="241" alt="Screenshot 2023-03-31 at 9 13 48 PM" src="https://user-images.githubusercontent.com/44798044/229189681-80f8c5e3-5dbd-4c0d-9eba-afc69eca3a41.png">

Your design:

<img width="241" alt="Screenshot 2023-03-31 at 9 13 48 PM" src="https://user-images.githubusercontent.com/44798044/229189651-c14fe331-4ad7-439f-90cc-3836556cd43a.png">

2023-03-31 17:45 UTC, shella12 commented on style.css
> +  line-height: 52px;
- [ ] Please add a bit of padding in the `technology categories` to match the figma design.

Figma design:
<img width="350" alt="Screenshot 2023-03-31 at 9 13 26 PM" src="https://user-images.githubusercontent.com/44798044/229190835-5e22c427-89ee-4aa2-8b48-66a152f8eab6.png">

Your design:

<img width="330" alt="Screenshot 2023-03-31 at 10 37 24 PM" src="https://user-images.githubusercontent.com/44798044/229191335-d36d345a-1380-4f57-8a0f-72fcae2140fa.png">

2023-04-01 02:27 UTC, didierganthier requested changes
Hi @mohashyne ,

🎉 You're working hard it seems 💪🏽 but you submitted the project without taking into consideration the previous reviewer's comments since no commits were added since them. Please make sure to take them into consideration and submit them again.

<img src="https://media.giphy.com/media/e56n4Z0mmkxZS/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- [ ] You're working hard it seems 💪🏽 but you submitted the project without taking into consideration the previous reviewer's comments since no commits were added since them. Please make sure to take them into consideration and submit again.

- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-04-01 06:30 UTC, mohashyne commented
@didierganthier  kindly check thoroughly , i have applied all the changes  requested by @shella12  , in regards to  this only :  " ( Please make sure the technology categories ("Languages", "Frameworks" and "Skills") are in one ul, and each of them in a li tag. And you can inclose. Like for example: 

 <ul>
<li>Languages</li>
<li>Frameworks</li>
<li>Skills</li>
</ul>) "


the structure will not work out perfectly, you can kindly clone the project and try it please.  you can use the ''outline" command in css to see things  clearly. Thank you 🙏

2023-04-01 08:32 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @mohashyne, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 08:32 UTC, Qoosim commented on index.html
> +           <div>
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

![your-let-connect](https://user-images.githubusercontent.com/26597432/229273758-20fcff68-7796-4d01-9fa0-64f910a7ebcf.png)

2023-04-01 08:32 UTC, Qoosim commented on index.html
> +        <p class="info">I'm a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

2023-04-01 08:32 UTC, Qoosim commented on index.html
> +                    </nav>
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

2023-04-01 08:32 UTC, Qoosim commented on index.html
> +                    </nav>
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

2023-04-01 08:32 UTC, Qoosim commented on index.html
> +                    </nav>
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

2023-04-01 08:32 UTC, Qoosim commented on style.css
> +}
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

2023-04-01 08:32 UTC, Qoosim commented on style.css
> +}
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

### Your Design
![your-back-end](https://user-images.githubusercontent.com/26597432/229274496-12701235-62b4-48f6-88a5-2b9b7aa312ad.png)

### Figma Design
![temp-back-end](https://user-images.githubusercontent.com/26597432/229274540-447a0ae8-0e98-456d-982e-a96e6c06ecda.png)

2023-04-01 08:32 UTC, Qoosim commented on style.css
> +  width: 214px;
- [ ] - [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

### Your Design
![your-project-spacing](https://user-images.githubusercontent.com/26597432/229274779-b9e2925f-eb60-4d4d-a001-3d06bec0aa08.png)

### Figma Design
![temp-spacing](https://user-images.githubusercontent.com/26597432/229274788-81d5d723-5aee-4d7c-94d2-ee14e6cf0658.png)

2023-04-01 08:32 UTC, Qoosim commented on style.css
> +}
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

### Your Design
[active-btn.webm](https://user-images.githubusercontent.com/26597432/229274887-725dce2e-10e8-4042-af78-63884b7c1e1b.webm)

2023-04-01 08:32 UTC, Qoosim commented on style.css
> +  flex-direction: row;
- [ ] This requested changes by the previous reviewer has not been implemented yet. Kindly attend to it.

### Your Design
![your-bg](https://user-images.githubusercontent.com/26597432/229275172-0ebdf77f-5808-4f20-8cff-b16b26ade02e.png)

2023-04-01 08:32 UTC, Qoosim commented on index.html
> +                    </nav>
- [ ] Something is happening here. There are some unwanted elements appearing here. Kindly look into it and fix.

### Your Design
![something](https://user-images.githubusercontent.com/26597432/229275278-59c75bfa-26ad-495b-890c-a23a968f07b4.png)

2023-04-01 11:41 UTC, didierganthier requested changes
Hi @mohashyne ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/e56n4Z0mmkxZS/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-04-01 11:41 UTC, didierganthier commented on style.css
> +  border-top-right-radius: 43px;
Seems like you're trying to apply the requested change about the rounded corner 👀 kudos on that 💯 but it's not showing up in the UI because you have some element behind it, this is what I get when I try to give it a red background 👇🏽 

![Screenshot 2023-04-01 at 07 31 14](https://user-images.githubusercontent.com/45739963/229286250-f693e308-55f7-46c2-a7bb-e688d09af6a4.png)

You can either try removing or changing the background of the element behind it. You can also give it the same border as this one. 🤓

2023-04-01 12:41 UTC, mohashyne commented on style.css
> +  border-top-right-radius: 43px;
Thanks for the clue, it has been fixed 👍

2023-04-01 13:00 UTC, KanzaTahreem approved these changes
# Approved 🥳

Hi @mohashyne 👋

Good job implementing the changes suggested by [previous reviewers. I would like to express my deep appreciation for the time and effort you dedicated to this project 💪

**_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Styling is looking great, perfect!
-  ✅ Great work using the right GitHub Flow 
-  ✅ Your README looks professional, well done!
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 13:03 UTC, merged